//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaFrba {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class ArchivoDeConfiguracion : global::System.Configuration.ApplicationSettingsBase {
        
        private static ArchivoDeConfiguracion defaultInstance = ((ArchivoDeConfiguracion)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ArchivoDeConfiguracion())));
        
        public static ArchivoDeConfiguracion Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gd")]
        public string UserDB {
            get {
                return ((string)(this["UserDB"]));
            }
            set {
                this["UserDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gd2016")]
        public string PassDB {
            get {
                return ((string)(this["PassDB"]));
            }
            set {
                this["PassDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GD2C2016")]
        public string InitialCatalogDB {
            get {
                return ((string)(this["InitialCatalogDB"]));
            }
            set {
                this["InitialCatalogDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\SQLSERVER2012")]
        public string SourceDB {
            get {
                return ((string)(this["SourceDB"]));
            }
            set {
                this["SourceDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20/11/2016")]
        public string Fecha {
            get {
                return ((string)(this["Fecha"]));
            }
            set {
                this["Fecha"] = value;
            }
        }
    }
}
